### ISSUE TITLE
List and Table selection behavior unexpected

### ISSUE THREAD

**Issue by ImmanuelMc** [richardwilkes/unison#10] opened 2022-09-07 19:42 UTC
Lists and tables behave unexpectedly when selecting multiple items. I believe I have fixes, but I have never contributed to a project before, so I have to figure that out still.

Issues:

What I expect: If control-A is pressed when everything is already selected, it should deselect all. 
What happens: Everything stays selected, nothing changes.
` `  
What I expect: If clicking on an already selected item, without holding down any keys, it should deselect everything except that item.
What happens: Everything stays selected, nothing changes.
` `   
What I expect: If I hold control while clicking an item, its selection status should toggle.
What happens: Everything stays selected, nothing changes.
I fixed this by changing CommandModifier to ControlModifier on my linux computer, but am unsure if that is the way to do it for cross platform.
` `  

In particular, these three things make it so if every item of a table is selected, it is impossible to deselect anything.

Other, less visible, issue:
NewSelectionCallback on lists gets called a lot without real changes and fails to get called in certain situations.
I fixed this by making sure changes to selection get passed through list methods instead of calling the Selection BitSet methods directly, and doing checks for changes, and callback notifications in the list methods. I am not sure if that is the best way to do it. This is most noticeable with the selection on mouse drag. It is called constantly as the mouse moves around even if it stays on the same row.
` `  
A similar problem happens with SelectionChangedCallback on tables, but haven't dived into that yet.

**Comment by richardwilkes** [comment] 2022-09-07 21:38
> Issues:
> 
> What I expect: If control-A is pressed when everything is already selected, it should deselect all.
> What happens: Everything stays selected, nothing changes.

Select All should never deselect. This is the intended behavior.

> What I expect: If clicking on an already selected item, without holding down any keys, it should deselect everything except that item.
> What happens: Everything stays selected, nothing changes.

Again, this is intended behavior. Without it, it is impossible to make a selection of more than one item and then drag those items elsewhere, since the act of clicking to start the drag would deselect all but the row clicked on.

> What I expect: If I hold control while clicking an item, its selection status should toggle.
> What happens: Everything stays selected, nothing changes.
> I fixed this by changing CommandModifier to ControlModifier on my linux computer, but am unsure if that is the way to do it for cross platform.

Hmm... this one should have been working as you describe. The "Command" modifier should be mapped to "Control" for Windows & Linux and use the actual command key on macOS. I'll take a look at that.

> Other, less visible, issue:
> NewSelectionCallback on lists gets called a lot without real changes and fails to get called in certain situations.
> I fixed this by making sure changes to selection get passed through list methods instead of calling the Selection BitSet methods directly, and doing checks for changes, and callback notifications in the list methods. I am not sure if that is the best way to do it. This is most noticeable with the selection on mouse drag. It is called constantly as the mouse moves around even if it stays on the same row.
> 
> A similar problem happens with SelectionChangedCallback on tables, but haven't dived into that yet.

I'll take a look at this as well. There are cases were I explicitly do not want the change to issue notifications, so a blanket approach is probably not the answer, but I may be recalling the cases incorrectly.

**Comment by ImmanuelMc** [comment] 2022-09-08 03:12
Thanks for your quick response.

If the logic for whether to select a row and deselect everything is put in DefaultMouseUp, it can be made to only trigger if the mouse doesn't move around or get held pressed too long. It is slightly more convenient than having to click off on something else, before clicking one of the selected items. I did a quick test to make sure it was feasible. If you think that would cause other issues, I will take your word for it. Am just looking for an entry level issue I can work on.

**Comment by richardwilkes** [comment] 2022-09-08 05:03
You are welcome to open a PR with the change you’re suggesting. It’s possible I’m not understanding what you’re proposing and having actual code to try out for myself would clear that up.

It does need to work on all 3 platforms (macOS, Windows & Linux). I do most of my work on macOS, because I prefer that platform, but I do have physical machines for each to develop and test with. For this sort of thing, I would hope there is no meaningful platform difference other than the command vs control key handling.

**Comment by richardwilkes** [comment] 2022-09-09 02:53
I looked at List.NewSelectionCallback and see that you must be referring to the keyboard handling cases, which indeed can call List.NewSelectionCallback when they don't need to. This is due to the fact that I don't record the previous state prior to any changes that may or may not occur due to the key press. This was done on the theory that it was potentially expensive to record the state for every key press when most of the time it wasn't needed. On the flip side, potentially triggering expensive logic in the callback could be just as bad. So... I should probably either go ahead and add that overhead, or change the keyboard handling such that it can know when it actually makes a change that matters.

Table.SelectionChangedCallback (I should really consolidate the naming!) has a similar issue, though has many more cases where it would need to record the state, which is likely to be prohibitive on large tables where a large number of rows have been selected... and at the same time, many of those operations would likely be as expensive or even more expensive to alter in a way that they could track that they actually made a change in the final state. I'm not sure it is beneficial to change anything in Table due to this, but it is certainly worth checking into.

**Comment by ImmanuelMc** [comment] 2022-09-11 21:11
It looks like the control click is not working because it calls CommandDown() instead of OSMenuCmdModifierDown() ? 

And the main source of extra selection change callbacks on keypress seems to be at the top and bottom of the list. I think I can write a check for the couple of cases that happen without having to save state, if would like.

**Comment by richardwilkes** [comment] 2022-09-14 03:50
The v0.30.1 release contains changes that address most of the items that from this thread.

I'm going to close this issue, however, I'm open to a PR to limit selection callbacks to avoid unnecessary notifications.

**Closed by richardwilkes** 2022-09-14 03:50 UTC
Labels: bug
